name: Deploy App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
 NODE_VERSION: 16.15.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:ci

      - run: npm run build
        env:
          REACT_APP_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
          REACT_APP_SWELL_STORE_ID: ${{ secrets.SWELL_STORE_ID }}
          REACT_APP_SWELL_PUBLIC_TOKEN: ${{ secrets.SWELL_PUBLIC_TOKEN }}
        
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      pages: write
    needs: build
    steps:
      - uses: actions/deploy-pages@v1
